#============DOCTORS============

#api call for listing doctors
###
GET http://127.0.0.1:8000/doctors/
Accept: application/json


#api call for creating doctor details
###
POST http://127.0.0.1:8000/doctors/ 
Content-Type: application/json

{
    "name": "Dr. Arun",
    "specialization": "pediatrics",
    "fee": 600,
    "qualification": "MBBS, MD Pediatrics",
    "email": "arun@gmail.com"
}

#api calls for retrieve doctor details
###
GET  http://127.0.0.1:8000/doctors/2/
Accept: application/json

#api calls for update doctor details
###
PUT http://127.0.0.1:8000/doctors/1/
Content-Type: application/json

{
    "name": "Dr Sooraj Das",
    "specialization": "radiology",
    "fee": 700,
    "qualification": "MBBS, MD radiology",
    "email": "soorajdas683@gmail.com"
}

#api calls for delete doctor deails
###
DELETE http://127.0.0.1:8000/doctors/2/


# v2 end points
###
GET http://127.0.0.1:8000/v2/doctors/
Accept: application/json


#api call for adding doctor details
###
POST http://127.0.0.1:8000/v2/doctors/ 
Content-Type: application/json

{
    "name": "Dr. Shaju",
    "specialization": "nephrology",
    "fee": 600,
    "qualification": "MBBS, MD nephrology",
    "email": "shaju@gmail.com"
}

#api call for retrieve doctor details
###
GET  http://127.0.0.1:8000/v2/doctors/4/
Accept: application/json


#api call for update doctor details
###
PUT  http://127.0.0.1:8000/v2/doctors/4/
Content-Type: application/json


{
  "id": "4",
  "name": "Dr. Ram krishna",
  "specialization": "ent",
  "fee": 550,
  "qualification": "MBBS, MS ENT",
  "email": "ramk@gmail.com"
}

#api call for creating admin user
###
POST http://127.0.0.1:8000/v2/admin-register/
Content-Type: application/json

{
    "username" : "admin",
    "email" : "admin@gmail.com",
    "password" : "admin@123"
}
