# Generated by Django 6.1.1 on 2026-09-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('ent', 'Ear, Nose & Throat (ENT)'), ('gastroenterology', 'Gastroenterology'), ('general_medicine', 'General Medicine / Internal Medicine'), ('general_surgery', 'General Surgery'), ('gynecology', 'Gynecology & Obstetrics'), ('hematology', 'Hematology'), ('nephrology', 'Nephrology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('ophthalmology', 'Ophthalmology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('pulmonology', 'Pulmonology'), ('radiology', 'Radiology'), ('urology', 'Urology'), ('other', 'Other')], default='other', max_length=200)),
                ('fee', models.PositiveIntegerField()),
                ('qualification', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
