# Generated by Django 6.1.1 on 2026-09-30 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('appointment_date', models.DateField()),
                ('token_number', models.PositiveIntegerField(editable=False, null=True)),
                ('appointment_time', models.TimeField(editable=False, null=True)),
                ('problem', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.doctor')),
            ],
        ),
    ]
